// <auto-generated />
using IPLocateNet.Inf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPLocateNet.Inf.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("IPLocateNet.Domain.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("SovereigntyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SovereigntyId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "AF",
                            Code3 = "AFG",
                            Name = "Afghanistan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AX",
                            Code3 = "ALA",
                            Name = "Aland Islands",
                            SovereigntyId = (ushort)2
                        },
                        new
                        {
                            Id = "AL",
                            Code3 = "ALB",
                            Name = "Albania",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DZ",
                            Code3 = "DZA",
                            Name = "Algeria",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AS",
                            Code3 = "ASM",
                            Name = "American Samoa",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "AD",
                            Code3 = "AND",
                            Name = "Andorra",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AO",
                            Code3 = "AGO",
                            Name = "Angola",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AI",
                            Code3 = "AIA",
                            Name = "Anguilla",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "AQ",
                            Code3 = "ATA",
                            Name = "Antarctica",
                            SovereigntyId = (ushort)5
                        },
                        new
                        {
                            Id = "AG",
                            Code3 = "ATG",
                            Name = "Antigua and Barbuda",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AR",
                            Code3 = "ARG",
                            Name = "Argentina",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AM",
                            Code3 = "ARM",
                            Name = "Armenia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AW",
                            Code3 = "ABW",
                            Name = "Aruba",
                            SovereigntyId = (ushort)6
                        },
                        new
                        {
                            Id = "AU",
                            Code3 = "AUS",
                            Name = "Australia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AT",
                            Code3 = "AUT",
                            Name = "Austria",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AZ",
                            Code3 = "AZE",
                            Name = "Azerbaijan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BS",
                            Code3 = "BHS",
                            Name = "Bahamas (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BH",
                            Code3 = "BHR",
                            Name = "Bahrain",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BD",
                            Code3 = "BGD",
                            Name = "Bangladesh",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BB",
                            Code3 = "BRB",
                            Name = "Barbados",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BY",
                            Code3 = "BLR",
                            Name = "Belarus",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BE",
                            Code3 = "BEL",
                            Name = "Belgium",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BZ",
                            Code3 = "BLZ",
                            Name = "Belize",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BJ",
                            Code3 = "BEN",
                            Name = "Benin",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BM",
                            Code3 = "BMU",
                            Name = "Bermuda",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "BT",
                            Code3 = "BTN",
                            Name = "Bhutan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BO",
                            Code3 = "BOL",
                            Name = "Bolivia (Plurinational State of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BQ",
                            Code3 = "BES",
                            Name = "Bonaire, Sint Eustatius, Saba",
                            SovereigntyId = (ushort)6
                        },
                        new
                        {
                            Id = "BA",
                            Code3 = "BIH",
                            Name = "Bosnia and Herzegovina",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BW",
                            Code3 = "BWA",
                            Name = "Botswana",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BV",
                            Code3 = "BVT",
                            Name = "Bouvet Island",
                            SovereigntyId = (ushort)7
                        },
                        new
                        {
                            Id = "BR",
                            Code3 = "BRA",
                            Name = "Brazil",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IO",
                            Code3 = "IOT",
                            Name = "British Indian Ocean Territory (the)",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "BN",
                            Code3 = "BRN",
                            Name = "Brunei Darussalam",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BG",
                            Code3 = "BGR",
                            Name = "Bulgaria",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BF",
                            Code3 = "BFA",
                            Name = "Burkina Faso",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BI",
                            Code3 = "BDI",
                            Name = "Burundi",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CV",
                            Code3 = "CPV",
                            Name = "Cabo Verde",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KH",
                            Code3 = "KHM",
                            Name = "Cambodia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CM",
                            Code3 = "CMR",
                            Name = "Cameroon",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CA",
                            Code3 = "CAN",
                            Name = "Canada",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KY",
                            Code3 = "CYM",
                            Name = "Cayman Islands (the)",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "CF",
                            Code3 = "CAF",
                            Name = "Central African Republic (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TD",
                            Code3 = "TCD",
                            Name = "Chad",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CL",
                            Code3 = "CHL",
                            Name = "Chile",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CN",
                            Code3 = "CHN",
                            Name = "China",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CX",
                            Code3 = "CXR",
                            Name = "Christmas Island",
                            SovereigntyId = (ushort)8
                        },
                        new
                        {
                            Id = "CC",
                            Code3 = "CCK",
                            Name = "Cocos (Keeling) Islands (the)",
                            SovereigntyId = (ushort)8
                        },
                        new
                        {
                            Id = "CO",
                            Code3 = "COL",
                            Name = "Colombia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KM",
                            Code3 = "COM",
                            Name = "Comoros (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CD",
                            Code3 = "COD",
                            Name = "Congo (the Democratic Republic of the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CG",
                            Code3 = "COG",
                            Name = "Congo (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CK",
                            Code3 = "COK",
                            Name = "Cook Islands (the)",
                            SovereigntyId = (ushort)9
                        },
                        new
                        {
                            Id = "CR",
                            Code3 = "CRI",
                            Name = "Costa Rica",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CI",
                            Code3 = "CIV",
                            Name = "Cote d'Ivoire",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "HR",
                            Code3 = "HRV",
                            Name = "Croatia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CU",
                            Code3 = "CUB",
                            Name = "Cuba",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CW",
                            Code3 = "CUW",
                            Name = "Curaçao",
                            SovereigntyId = (ushort)6
                        },
                        new
                        {
                            Id = "CY",
                            Code3 = "CYP",
                            Name = "Cyprus",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CZ",
                            Code3 = "CZE",
                            Name = "Czechia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DK",
                            Code3 = "DNK",
                            Name = "Denmark",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DJ",
                            Code3 = "DJI",
                            Name = "Djibouti",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DM",
                            Code3 = "DMA",
                            Name = "Dominica",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DO",
                            Code3 = "DOM",
                            Name = "Dominican Republic (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "EC",
                            Code3 = "ECU",
                            Name = "Ecuador",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "EG",
                            Code3 = "EGY",
                            Name = "Egypt",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SV",
                            Code3 = "SLV",
                            Name = "El Salvador",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GQ",
                            Code3 = "GNQ",
                            Name = "Equatorial Guinea",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ER",
                            Code3 = "ERI",
                            Name = "Eritrea",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "EE",
                            Code3 = "EST",
                            Name = "Estonia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SZ",
                            Code3 = "SWZ",
                            Name = "Eswatini",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ET",
                            Code3 = "ETH",
                            Name = "Ethiopia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "FK",
                            Code3 = "FLK",
                            Name = "Falkland Islands (the)",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "FO",
                            Code3 = "FRO",
                            Name = "Faroe Islands (the)",
                            SovereigntyId = (ushort)10
                        },
                        new
                        {
                            Id = "FJ",
                            Code3 = "FJI",
                            Name = "Fiji",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "FI",
                            Code3 = "FIN",
                            Name = "Finland",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "FR",
                            Code3 = "FRA",
                            Name = "France",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GF",
                            Code3 = "GUF",
                            Name = "French Guiana",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "PF",
                            Code3 = "PYF",
                            Name = "French Polynesia",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "TF",
                            Code3 = "ATF",
                            Name = "French Southern Territories (the)",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "GA",
                            Code3 = "GAB",
                            Name = "Gabon",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GM",
                            Code3 = "GMB",
                            Name = "Gambia (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GE",
                            Code3 = "GEO",
                            Name = "Georgia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "DE",
                            Code3 = "DEU",
                            Name = "Germany",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GH",
                            Code3 = "GHA",
                            Name = "Ghana",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GI",
                            Code3 = "GIB",
                            Name = "Gibraltar",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "GR",
                            Code3 = "GRC",
                            Name = "Greece",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GL",
                            Code3 = "GRL",
                            Name = "Greenland",
                            SovereigntyId = (ushort)10
                        },
                        new
                        {
                            Id = "GD",
                            Code3 = "GRD",
                            Name = "Grenada",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GP",
                            Code3 = "GLP",
                            Name = "Guadeloupe",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "GU",
                            Code3 = "GUM",
                            Name = "Guam",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "GT",
                            Code3 = "GTM",
                            Name = "Guatemala",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GG",
                            Code3 = "GGY",
                            Name = "Guernsey",
                            SovereigntyId = (ushort)12
                        },
                        new
                        {
                            Id = "GN",
                            Code3 = "GIN",
                            Name = "Guinea",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GW",
                            Code3 = "GNB",
                            Name = "Guinea-Bissau",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GY",
                            Code3 = "GUY",
                            Name = "Guyana",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "HT",
                            Code3 = "HTI",
                            Name = "Haiti",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "HM",
                            Code3 = "HMD",
                            Name = "Heard Island and McDonald Islands",
                            SovereigntyId = (ushort)8
                        },
                        new
                        {
                            Id = "VA",
                            Code3 = "VAT",
                            Name = "Holy See (the)",
                            SovereigntyId = (ushort)13
                        },
                        new
                        {
                            Id = "HN",
                            Code3 = "HND",
                            Name = "Honduras",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "HK",
                            Code3 = "HKG",
                            Name = "Hong Kong",
                            SovereigntyId = (ushort)14
                        },
                        new
                        {
                            Id = "HU",
                            Code3 = "HUN",
                            Name = "Hungary",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IS",
                            Code3 = "ISL",
                            Name = "Iceland",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IN",
                            Code3 = "IND",
                            Name = "India",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ID",
                            Code3 = "IDN",
                            Name = "Indonesia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IR",
                            Code3 = "IRN",
                            Name = "Iran (Islamic Republic of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IQ",
                            Code3 = "IRQ",
                            Name = "Iraq",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IE",
                            Code3 = "IRL",
                            Name = "Ireland",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IM",
                            Code3 = "IMN",
                            Name = "Isle of Man",
                            SovereigntyId = (ushort)12
                        },
                        new
                        {
                            Id = "IL",
                            Code3 = "ISR",
                            Name = "Israel",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "IT",
                            Code3 = "ITA",
                            Name = "Italy",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "JM",
                            Code3 = "JAM",
                            Name = "Jamaica",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "JP",
                            Code3 = "JPN",
                            Name = "Japan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "JE",
                            Code3 = "JEY",
                            Name = "Jersey",
                            SovereigntyId = (ushort)12
                        },
                        new
                        {
                            Id = "JO",
                            Code3 = "JOR",
                            Name = "Jordan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KZ",
                            Code3 = "KAZ",
                            Name = "Kazakhstan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KE",
                            Code3 = "KEN",
                            Name = "Kenya",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KI",
                            Code3 = "KIR",
                            Name = "Kiribati",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KP",
                            Code3 = "PRK",
                            Name = "Korea (the Democratic People's Republic of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KR",
                            Code3 = "KOR",
                            Name = "Korea (the Republic of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KW",
                            Code3 = "KWT",
                            Name = "Kuwait",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "KG",
                            Code3 = "KGZ",
                            Name = "Kyrgyzstan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LA",
                            Code3 = "LAO",
                            Name = "Lao People's Democratic Republic (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LV",
                            Code3 = "LVA",
                            Name = "Latvia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LB",
                            Code3 = "LBN",
                            Name = "Lebanon",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LS",
                            Code3 = "LSO",
                            Name = "Lesotho",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LR",
                            Code3 = "LBR",
                            Name = "Liberia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LY",
                            Code3 = "LBY",
                            Name = "Libya",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LI",
                            Code3 = "LIE",
                            Name = "Liechtenstein",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LT",
                            Code3 = "LTU",
                            Name = "Lithuania",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LU",
                            Code3 = "LUX",
                            Name = "Luxembourg",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MO",
                            Code3 = "MAC",
                            Name = "Macao",
                            SovereigntyId = (ushort)14
                        },
                        new
                        {
                            Id = "MG",
                            Code3 = "MDG",
                            Name = "Madagascar",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MW",
                            Code3 = "MWI",
                            Name = "Malawi",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MY",
                            Code3 = "MYS",
                            Name = "Malaysia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MV",
                            Code3 = "MDV",
                            Name = "Maldives",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ML",
                            Code3 = "MLI",
                            Name = "Mali",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MT",
                            Code3 = "MLT",
                            Name = "Malta",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MH",
                            Code3 = "MHL",
                            Name = "Marshall Islands (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MQ",
                            Code3 = "MTQ",
                            Name = "Martinique",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "MR",
                            Code3 = "MRT",
                            Name = "Mauritania",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MU",
                            Code3 = "MUS",
                            Name = "Mauritius",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "YT",
                            Code3 = "MYT",
                            Name = "Mayotte",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "MX",
                            Code3 = "MEX",
                            Name = "Mexico",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "FM",
                            Code3 = "FSM",
                            Name = "Micronesia (Federated States of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MD",
                            Code3 = "MDA",
                            Name = "Moldova (the Republic of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MC",
                            Code3 = "MCO",
                            Name = "Monaco",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MN",
                            Code3 = "MNG",
                            Name = "Mongolia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ME",
                            Code3 = "MNE",
                            Name = "Montenegro",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MS",
                            Code3 = "MSR",
                            Name = "Montserrat",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "MA",
                            Code3 = "MAR",
                            Name = "Morocco",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MZ",
                            Code3 = "MOZ",
                            Name = "Mozambique",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MM",
                            Code3 = "MMR",
                            Name = "Myanmar",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NA",
                            Code3 = "NAM",
                            Name = "Namibia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NR",
                            Code3 = "NRU",
                            Name = "Nauru",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NP",
                            Code3 = "NPL",
                            Name = "Nepal",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NL",
                            Code3 = "NLD",
                            Name = "Netherlands (Kingdom of the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NC",
                            Code3 = "NCL",
                            Name = "New Caledonia",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "NZ",
                            Code3 = "NZL",
                            Name = "New Zealand",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NI",
                            Code3 = "NIC",
                            Name = "Nicaragua",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NE",
                            Code3 = "NER",
                            Name = "Niger (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NG",
                            Code3 = "NGA",
                            Name = "Nigeria",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "NU",
                            Code3 = "NIU",
                            Name = "Niue",
                            SovereigntyId = (ushort)9
                        },
                        new
                        {
                            Id = "NF",
                            Code3 = "NFK",
                            Name = "Norfolk Island",
                            SovereigntyId = (ushort)8
                        },
                        new
                        {
                            Id = "MP",
                            Code3 = "MNP",
                            Name = "Northern Mariana Islands (the)",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "NO",
                            Code3 = "NOR",
                            Name = "Norway",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MK",
                            Code3 = "MKD",
                            Name = "North Macedonia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "OM",
                            Code3 = "OMN",
                            Name = "Oman",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PK",
                            Code3 = "PAK",
                            Name = "Pakistan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PW",
                            Code3 = "PLW",
                            Name = "Palau",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PS",
                            Code3 = "PSE",
                            Name = "Palestine, State of",
                            SovereigntyId = (ushort)13
                        },
                        new
                        {
                            Id = "PA",
                            Code3 = "PAN",
                            Name = "Panama",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PG",
                            Code3 = "PNG",
                            Name = "Papua New Guinea",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PY",
                            Code3 = "PRY",
                            Name = "Paraguay",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PE",
                            Code3 = "PER",
                            Name = "Peru",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PH",
                            Code3 = "PHL",
                            Name = "Philippines (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PN",
                            Code3 = "PCN",
                            Name = "Pitcairn",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "PL",
                            Code3 = "POL",
                            Name = "Poland",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PT",
                            Code3 = "PRT",
                            Name = "Portugal",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "PR",
                            Code3 = "PRI",
                            Name = "Puerto Rico",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "QA",
                            Code3 = "QAT",
                            Name = "Qatar",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "RE",
                            Code3 = "REU",
                            Name = "Reunion",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "RO",
                            Code3 = "ROU",
                            Name = "Romania",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "RU",
                            Code3 = "RUS",
                            Name = "Russian Federation (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "RW",
                            Code3 = "RWA",
                            Name = "Rwanda",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "BL",
                            Code3 = "BLM",
                            Name = "Saint Barthelemy",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "KN",
                            Code3 = "KNA",
                            Name = "Saint Kitts and Nevis",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LC",
                            Code3 = "LCA",
                            Name = "Saint Lucia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "MF",
                            Code3 = "MAF",
                            Name = "Saint Martin (French part)",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "PM",
                            Code3 = "SPM",
                            Name = "Saint Pierre and Miquelon",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "VC",
                            Code3 = "VCT",
                            Name = "Saint Vincent and the Grenadines",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SH",
                            Code3 = "SHN",
                            Name = "Saint Helena, Ascension Island, Tristan da Cunha",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "WS",
                            Code3 = "WSM",
                            Name = "Samoa",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SM",
                            Code3 = "SMR",
                            Name = "San Marino",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ST",
                            Code3 = "STP",
                            Name = "Sao Tome and Principe",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SA",
                            Code3 = "SAU",
                            Name = "Saudi Arabia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SN",
                            Code3 = "SEN",
                            Name = "Senegal",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "RS",
                            Code3 = "SRB",
                            Name = "Serbia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SC",
                            Code3 = "SYC",
                            Name = "Seychelles",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SL",
                            Code3 = "SLE",
                            Name = "Sierra Leone",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SG",
                            Code3 = "SGP",
                            Name = "Singapore",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SX",
                            Code3 = "SXM",
                            Name = "Sint Maarten (Dutch part)",
                            SovereigntyId = (ushort)6
                        },
                        new
                        {
                            Id = "SK",
                            Code3 = "SVK",
                            Name = "Slovakia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SI",
                            Code3 = "SVN",
                            Name = "Slovenia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SB",
                            Code3 = "SLB",
                            Name = "Solomon Islands",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SO",
                            Code3 = "SOM",
                            Name = "Somalia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ZA",
                            Code3 = "ZAF",
                            Name = "South Africa",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GS",
                            Code3 = "SGS",
                            Name = "South Georgia and the South Sandwich Islands",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "SS",
                            Code3 = "SSD",
                            Name = "South Sudan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ES",
                            Code3 = "ESP",
                            Name = "Spain",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "LK",
                            Code3 = "LKA",
                            Name = "Sri Lanka",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SD",
                            Code3 = "SDN",
                            Name = "Sudan (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SR",
                            Code3 = "SUR",
                            Name = "Suriname",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SJ",
                            Code3 = "SJM",
                            Name = "Svalbard, Jan Mayen",
                            SovereigntyId = (ushort)7
                        },
                        new
                        {
                            Id = "SE",
                            Code3 = "SWE",
                            Name = "Sweden",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "CH",
                            Code3 = "CHE",
                            Name = "Switzerland",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "SY",
                            Code3 = "SYR",
                            Name = "Syrian Arab Republic (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TW",
                            Code3 = "TWN",
                            Name = "Taiwan (Province of China)",
                            SovereigntyId = (ushort)15
                        },
                        new
                        {
                            Id = "TJ",
                            Code3 = "TJK",
                            Name = "Tajikistan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TZ",
                            Code3 = "TZA",
                            Name = "Tanzania, the United Republic of",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TH",
                            Code3 = "THA",
                            Name = "Thailand",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TL",
                            Code3 = "TLS",
                            Name = "Timor-Leste",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TG",
                            Code3 = "TGO",
                            Name = "Togo",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TK",
                            Code3 = "TKL",
                            Name = "Tokelau",
                            SovereigntyId = (ushort)9
                        },
                        new
                        {
                            Id = "TO",
                            Code3 = "TON",
                            Name = "Tonga",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TT",
                            Code3 = "TTO",
                            Name = "Trinidad and Tobago",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TN",
                            Code3 = "TUN",
                            Name = "Tunisia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TR",
                            Code3 = "TUR",
                            Name = "Turkiye",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TM",
                            Code3 = "TKM",
                            Name = "Turkmenistan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "TC",
                            Code3 = "TCA",
                            Name = "Turks and Caicos Islands (the)",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "TV",
                            Code3 = "TUV",
                            Name = "Tuvalu",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "UG",
                            Code3 = "UGA",
                            Name = "Uganda",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "UA",
                            Code3 = "UKR",
                            Name = "Ukraine",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "AE",
                            Code3 = "ARE",
                            Name = "United Arab Emirates (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "GB",
                            Code3 = "GBR",
                            Name = "United Kingdom of Great Britain and Northern Ireland (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "UM",
                            Code3 = "UMI",
                            Name = "United States Minor Outlying Islands (the)",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "US",
                            Code3 = "USA",
                            Name = "United States of America (the)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "UY",
                            Code3 = "URY",
                            Name = "Uruguay",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "UZ",
                            Code3 = "UZB",
                            Name = "Uzbekistan",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "VU",
                            Code3 = "VUT",
                            Name = "Vanuatu",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "VE",
                            Code3 = "VEN",
                            Name = "Venezuela (Bolivarian Republic of)",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "VN",
                            Code3 = "VNM",
                            Name = "Viet Nam",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "VG",
                            Code3 = "VGB",
                            Name = "Virgin Islands (British)",
                            SovereigntyId = (ushort)4
                        },
                        new
                        {
                            Id = "VI",
                            Code3 = "VIR",
                            Name = "Virgin Islands (U.S.)",
                            SovereigntyId = (ushort)3
                        },
                        new
                        {
                            Id = "WF",
                            Code3 = "WLF",
                            Name = "Wallis and Futuna",
                            SovereigntyId = (ushort)11
                        },
                        new
                        {
                            Id = "EH",
                            Code3 = "ESH",
                            Name = "Western Sahara",
                            SovereigntyId = (ushort)15
                        },
                        new
                        {
                            Id = "YE",
                            Code3 = "YEM",
                            Name = "Yemen",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ZM",
                            Code3 = "ZMB",
                            Name = "Zambia",
                            SovereigntyId = (ushort)1
                        },
                        new
                        {
                            Id = "ZW",
                            Code3 = "ZWE",
                            Name = "Zimbabwe",
                            SovereigntyId = (ushort)1
                        });
                });

            modelBuilder.Entity("IPLocateNet.Domain.IPv4Range", b =>
                {
                    b.Property<byte[]>("StartingIP")
                        .HasColumnType("BLOB");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EndingIP")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("StartingIP");

                    b.HasIndex("CountryId");

                    b.ToTable("IPv4Ranges");
                });

            modelBuilder.Entity("IPLocateNet.Domain.Sovereignty", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sovereignties");

                    b.HasData(
                        new
                        {
                            Id = (ushort)1,
                            Name = "UN member"
                        },
                        new
                        {
                            Id = (ushort)2,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = (ushort)3,
                            Name = "United States"
                        },
                        new
                        {
                            Id = (ushort)4,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = (ushort)5,
                            Name = "Antarctic Treaty"
                        },
                        new
                        {
                            Id = (ushort)6,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = (ushort)7,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = (ushort)8,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = (ushort)9,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = (ushort)10,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = (ushort)11,
                            Name = "France"
                        },
                        new
                        {
                            Id = (ushort)12,
                            Name = "British Crown"
                        },
                        new
                        {
                            Id = (ushort)13,
                            Name = "UN observer"
                        },
                        new
                        {
                            Id = (ushort)14,
                            Name = "China"
                        },
                        new
                        {
                            Id = (ushort)15,
                            Name = "Disputed"
                        });
                });

            modelBuilder.Entity("IPLocateNet.Domain.Country", b =>
                {
                    b.HasOne("IPLocateNet.Domain.Sovereignty", "Sovereignty")
                        .WithMany()
                        .HasForeignKey("SovereigntyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sovereignty");
                });

            modelBuilder.Entity("IPLocateNet.Domain.IPv4Range", b =>
                {
                    b.HasOne("IPLocateNet.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
